### ISSUE TITLE
There was an error parsing JSON document

### ISSUE THREAD

**Issue by pwqw** [jibon57/Joomla_API#1]
Se produjo un error al analizar el documento JSON. El documento podría no estar bien formateado.
unexpected character at line 1 column 1

``` html
<br />
<b>Strict Standards</b>:  Only variables should be assigned by reference in <b>/home/theuser/public_html/components/com_hoicoiapi/controller.php</b> on line <b>257</b><br />
[{"article_id":"1","title":"Cacaguates","introtext":"","fulltext":"2","language":null,"featured":null,"hits":""}]
```

<b>Strict Standards</b>:  Only variables should be assigned by reference in <b>/home/theuser/public_html/components/com_hoicoiapi/controller.php</b> on line <b>257</b><br />
[{"article_id":"1","title":"Cacaguates","introtext":"","fulltext":"2","language":null,"featured":null,"hits":""}]

**Comment by jibon57** [comment]
Thanks AlexisCaffa for reporting. I fixed that already :) .. Please download new archive :)
