### ISSUE TITLE
K2 Items in a category not working

### ISSUE THREAD

**Issue by sethvanstaden91** [jibon57/Joomla_API#3]
Are there any known issues around the K2 items in category? I installed the extension yesterday where items in category was working but today it is just returning an empty array. k2 single items is also returning an empty array. listing categories, however still works.

here is the items in category http://saharasystems.co.za/tna/index.php?option=com_hoicoiapi&task=k2_items&catid=3 //does not work | returns empty array

and categories http://saharasystems.co.za/tna/index.php?option=com_hoicoiapi&task=k2_categories //which do work 

*Edit: Ok I see that if I go to category 3 which only acts as a parent category for other categories: ?option=com_hoicoiapi&task=k2_items&catid=3 does not list categories though? Is there any way to display the child categories of a parent?

**Comment by jibon57** [comment]
Give a try now :)

**Comment by sethvanstaden91** [comment]
Thanx for the reply :) I just reinstalled from the Git page and a parent category is still returning an empty array rather than the child categories :/ when on the website I click on a parent category it lists out a page with the child categories and their articles but still receive the empty array when I make a call to the parent 'id'

**Comment by jibon57** [comment]
Please open a support ticket here: https://extensions.hoicoimasti.com/support.html
And include temporary access information of your Joomla site with FTP.
