### ISSUE TITLE
Joomla Star Rating form

### ISSUE THREAD

**Issue by umh** [jibon57/Joomla_API#4]
Hi,

Can you please guide or update your repository with joomla rating system. Love your API!

**Comment by jibon57** [comment]
@umh, Sorry for late response. Will you please explain little bit more? I don't think you are facing any problem with the extension.

**Comment by umh** [comment]
Hi,
There is no issue for the features the extension offers, however i would like to add default Joomla voting plugin support for it, so that we get current rating of the article, submitting a vote and updating the article rating after submission.

**Comment by jibon57** [comment]
@umh If you check this method: components/com_content/models/article.php line 266

`public function storeVote($pk = 0, $rate = 0)`

You will understand how to do that. Just make a new public method in Hoicoi Api & call storeVote method for counting vote :)
